ruby/micro-twitter-app/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]
end

ruby/micro-twitter-app/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

ruby/micro-twitter-app/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

ruby/micro-twitter-app/app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

ruby/micro-twitter-app/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following">
      <%= @user.following.count %>
    </strong> following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers">
      <%= @user.followers.count %>
    </strong> followers
  </a>
</div>

ruby/micro-twitter-app/app/views/shared/_user_info.html.erb
<h1><%= gravatar_for(current_user, size: 50) %> <%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>